version: '3.8'

services:
  bloglist-backend-dev:
    image: bloglist-backend-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3001:3001
    container_name: bloglist-backend-dev
