# fly.toml file generated for myveryownblogapp on 2023-04-23T20:33:56+02:00

app = "myveryownblogapp"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"
processes = []

[env]
  PORT = "8080"
  MONGODB_URI = "mongodb+srv://dynamo:appdatabase123@cluster0.givzdhk.mongodb.net/blogApp?retryWrites=true&w=majority"
  SECRET = "SEKRET"

[experimental]
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [deploy]
  release_command = "npm run build"

  [processes]
    app = "node backend/index.js"

  [build]
    [build.args]
      NODE_VERSION = "16.19.0"

  [[services.http_checks]]
  interval = 10000
  grace_period = "5s"
  method = "get"
  path = "/"
  protocol = "http"
  restart_limit = 0
  timeout = 2000
  tls_skip_verify = false
  [services.http_checks.headers]

[[services.http_checks]]
  name = "version_check"
  interval = "15s"
  grace_period = "30s"
  method = "get"
  path = "/health"
  protocol = "http"
  timeout = "10s"
  restart_limit = 0
  tls_skip_verify = false

