# fly.toml file generated for myveryownblogapp on 2023-04-23T20:33:56+02:00

app = "myveryownblogapp"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "cdg"
processes = []

[env]
  PORT = "8080"
  MONGODB_URI = "mongodb+srv://dynamo:appdatabase123@cluster0.givzdhk.mongodb.net/blogApp?retryWrites=true&w=majority"
  SECRET = "SEKRET"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
