name: Daily Health Check

on:
  schedule:
    - cron: '0 0 * * *' # Run health check every 24 hours at midnight (00:00)
    
jobs:
  health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://myveryownpokedex.fly.dev
          follow-redirect: false
          max-attempts: 3
          retry-delay: 5s
          retry-all: false